sudo: false
language: cpp

matrix:
  allow_failures:
    - env: _CXX=clang++-3.8 _CC=clang-3.8
  include:
    - env: _CXX=g++-5 _CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources: &sources
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
    - env: _CXX=clang++-3.7 _CC=clang-3.7
      addons:
        apt:
          packages:
            - clang-3.7
          sources: *sources
    # Clang trunk (allowed to fail)
    - env: _CXX=clang++-3.8 _CC=clang-3.8
      addons:
        apt:
          packages:
            - clang-3.8
          sources: *sources

install:
  - export PATH="$HOME/bin:$PATH"
  - export CXX="$_CXX" CC="$_CC"
  -
  - mkdir ~/bin
  - wget --no-check-certificate --no-clobber -O /tmp/tools/waf https://waf.io/waf-1.8.14 || true
  - install -t ~/bin /tmp/tools/waf

script:
  - waf configure
  - waf --build-test
  - build/tester

cache:
  apt: true
  directories:
    - /tmp/tools
