sudo: false
language: cpp

matrix:
  include:
    - env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
          sources:
            - ubuntu-toolchain-r-test
    - env: COMPILER_NAME=clang CXX=clang++-3.7 CC=clang-3.7
      addons:
        apt:
          packages:
            - clang-3.7
          sources:
            - llvm-toolchain-precise-3.7

install:
  - mkdir ~/bin
  - wget --no-check-certificate --no-clobber -O /tmp/tools/waf https://waf.io/waf-1.8.14 || true
  - install -t ~/bin /tmp/tools/waf

script:
  - waf configure
  - waf --build-test

cache:
  apt: true
  directories:
    - /tmp/tools

env:
  - PATH="$HOME/bin:$PATH"
