#---------------------------------#
#      general configuration      #
#---------------------------------#

# version format
version: "{build}"

#---------------------------------#
#    environment configuration    #
#---------------------------------#

os: Visual Studio 2015

# scripts that run after cloning repository
install:
  - curl -fsSL -o waf "https://waf.io/waf-1.8.15"
  - echo %PATH%

#---------------------------------#
#       build configuration       #
#---------------------------------#

# to add several platforms to build matrix:
platform:
  - x86
  - x64

# to run your custom scripts instead of automatic MSBuild
build_script:
  - python waf configure
  - python waf

#---------------------------------#
#       tests configuration       #
#---------------------------------#

# to run your custom scripts instead of automatic tests
test_script:
  - build\cpponfig_test.exe

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: build\libcpponfig.a

#---------------------------------#
#     deployment configuration    #
#---------------------------------#

# to disable deployment
deploy: off

#---------------------------------#
#        global handlers          #
#---------------------------------#

on_failure:
  - type build\config.log

#---------------------------------#
#         notifications           #
#---------------------------------#

notifications:
  # Email
  - provider: Email
    to:
      - nabijaczleweli@gmail.com
    subject: 'Build {{status}}'                  # optional
    message: "{{message}}, {{commitId}}, ..."    # optional
    on_build_status_changed: true
